### ISSUE TITLE
Provide code for generating plans via PDDL+LLM 

### ISSUE THREAD

**Issue by ruinianxu** [GuanSuns/LLMs-World-Models-for-Planning#1]
Hi @GuanSuns , this is an amazing work and thanks for opensourcing. I wonder whether you have a plan about providing the code for generating plans via LLM (outputs goals) and PDDL planners.

**Comment by GuanSuns** [comment]
@ruinianxu Hi Ruinian, thanks for your interest in our work. We plan to release the full set of code in late September (as the paper is still under review, and although unlikely, may need to be revised based on feedback).
