### ISSUE TITLE
Generating pddl_for_annotations.json

### ISSUE THREAD

**Issue by RAraghavarora** [GuanSuns/LLMs-World-Models-for-Planning#3]
Greetings,
I am trying to run the code using GPT-4 for the household domain, and I am interested in the LLM outputs for this domain. I am able to run the Step-1 by running construct_action_models.py.
For step-2, could you share how we can construct the feedback file: pddl_for_annotations.json? The outputs of step-1 contain a lot of actions, and iterations.

Alternatively, could you share a sample domain file that you got from GPT-4 for the household domain?
Thank you for your work.

**Comment by GuanSuns** [comment]
Hi @RAraghavarora , thanks for your interest in our work!

`pddl_for_annotations.json` is automatically generated at the end of step 1 (if you look at the last few lines in `construct_action_models.py`). It should have the final PDDL model as well as the translated version.

As we explain in the paper, the goal of step 2 is to correct factual errors with human feedback. There is no automated way to generate human feedback. So you will need to manually provide the feedback and populate the `annotation` field (i.e., a list) of each action in `pddl_for_annotations.json`. You can also look at `correct_action_models.py` to get a sense of how the `annotation` is going to be used.

Regarding sample domain files for all the domains, we actually list all the generated PDDL action models in the appendix of the paper. For the household domain, it should start from page 20.

**Comment by RAraghavarora** [comment]
Alright!
Thank you for the response. I had missed the files in the appendix.
